name: "C++ Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Build C++
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC Multi-platform Library
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

    - name: Make NachOS
      run: cd NachOS-4.0/code/build.linux && make depend && make
      
